// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: createchirps.sql

package database

import (
	"context"
	"database/sql"
	"time"
)

const createChirp = `-- name: CreateChirp :one
INSERT INTO chirps (created_at, updated_at, body, user_id, author_id)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, created_at, updated_at, body, user_id, author_id
`

type CreateChirpParams struct {
	CreatedAt time.Time
	UpdatedAt time.Time
	Body      string
	UserID    sql.NullInt32
	AuthorID  int32
}

func (q *Queries) CreateChirp(ctx context.Context, arg CreateChirpParams) (Chirp, error) {
	row := q.db.QueryRowContext(ctx, createChirp,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.Body,
		arg.UserID,
		arg.AuthorID,
	)
	var i Chirp
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Body,
		&i.UserID,
		&i.AuthorID,
	)
	return i, err
}
