// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: retrievechirps.sql

package database

import (
	"context"
)

const retrieveChirps = `-- name: RetrieveChirps :many
SELECT id, created_at, updated_at, body, user_id, author_id FROM chirps
WHERE author_id = $1 OR $1 = 0
ORDER BY created_at ASC
`

func (q *Queries) RetrieveChirps(ctx context.Context, authorID int32) ([]Chirp, error) {
	rows, err := q.db.QueryContext(ctx, retrieveChirps, authorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Chirp
	for rows.Next() {
		var i Chirp
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Body,
			&i.UserID,
			&i.AuthorID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
