// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: upgradeuser.sql

package database

import (
	"context"
	"database/sql"
)

const upgradeUser = `-- name: UpgradeUser :execresult
UPDATE users SET is_chirpy_red = TRUE WHERE id = $1
`

func (q *Queries) UpgradeUser(ctx context.Context, id int32) (sql.Result, error) {
	return q.db.ExecContext(ctx, upgradeUser, id)
}
